apiVersion: v1
kind: Pod
metadata:
  name: lxyustc-pod-manual
spec:
  containers:
  - name: lxyustc-pod-manual
    image: lxyustc.registrydomain.com:5000/test-image:v0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
