apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-demo-pod-v2
  labels:
    probe: http-based-liveness-probe
spec:
  containers:
  - name: liveness-probe-demo-pod-container
    image: lxyustc.registrydomain.com:5000/test-image-liveness-demo:v0.1
    livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 20
        failureThreshold: 4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
