apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replicationcontroller-without-selector
spec:
  replicas: 3
  template:
    metadata:
      name: lxyustc
      labels:
        kubernetes.actions.rc-app: lxyustc-test-app
    spec:
      containers:
        - name: lxyustc-container
          image: lxyustc.registrydomain.com:5000/test-image:v0.1
          ports:
            - containerPort: 8080
