apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  restartPolicy: OnFailure
  containers:
  - image: lxyustc.registrydomain.com:5000/nvidia/l4t-base:r32.4.3
    name: pod1-ctr
    command: ["sleep"]
    args: ["30"]

    resources:
      limits:
        nvidia.com/gpu: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  restartPolicy: OnFailure
  containers:
  - image: lxyustc.registrydomain.com:5000/nvidia/l4t-base:r32.4.3
    name: pod2-ctr
    command: ["sleep"]
    args: ["30"]

    resources:
      limits:
        nvidia.com/gpu: 1