apiVersion: v1
kind: Pod
metadata:
        name: query-pod
spec:
        restartPolicy: OnFailure
        containers:
        - image: jitteam/devicequery
          name: query-ctr

          resources:
                  limits:
                          nvidia.com/gpu: 1